[project]
name = "music-visualizer"
version = "0.1.0"
description = "Generate visuals from music"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "librosa>=0.11.0",
    "moviepy>=1.0.3",
    "pillow>=9.2,<12.0",
]
